// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCc7RUgreTnA2GymwDOqi1rQ05-GjuuXts',
    appId: '1:601249425483:web:89ca6ca172ab8c0ada85ce',
    messagingSenderId: '601249425483',
    projectId: 'viwi-c867a',
    authDomain: 'viwi-c867a.firebaseapp.com',
    storageBucket: 'viwi-c867a.appspot.com',
    measurementId: 'G-E5P120S1NL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAaoAvHhw4wapOXsy6WQII-Ig485KPZcpI',
    appId: '1:601249425483:android:39650d8ecd6d3c60da85ce',
    messagingSenderId: '601249425483',
    projectId: 'viwi-c867a',
    storageBucket: 'viwi-c867a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAk1QrL9B5eIGmk-g7R5HbX_jQjzRFcJIA',
    appId: '1:601249425483:ios:87339430cdf936ecda85ce',
    messagingSenderId: '601249425483',
    projectId: 'viwi-c867a',
    storageBucket: 'viwi-c867a.appspot.com',
    iosClientId: '601249425483-qjssqpif0n4bggsj1r3mb686il8rnopj.apps.googleusercontent.com',
    iosBundleId: 'com.example.viwi',
  );
}
